//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wii.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PHUONGTHAO-PC;Initial Catalog=Wii;Persist Security Info=True;User ID=" +
            "sa;Password=@dmin123;Connect Timeout=300")]
        public string WiiConnectionString {
            get {
                return ((string)(this["WiiConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\XING-MVN\\WiiDB\\output\\")]
        public string ThreeDSTSV_出力パス {
            get {
                return ((string)(this["ThreeDSTSV_出力パス"]));
            }
            set {
                this["ThreeDSTSV_出力パス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\ZZXSVMYV\\Desktop\\LINH\\WiiDB\\hailt\\rank\\")]
        public string ThreeDSTSV_ランキングボード用パス {
            get {
                return ((string)(this["ThreeDSTSV_ランキングボード用パス"]));
            }
            set {
                this["ThreeDSTSV_ランキングボード用パス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\ZZXSVMYV\\Desktop\\LINH\\WiiDB\\hailt\\history\\singlebefore\\3DS歌手.tsv")]
        public string ThreeDSTSV_歌手変更履歴取得元歌手TSVパス {
            get {
                return ((string)(this["ThreeDSTSV_歌手変更履歴取得元歌手TSVパス"]));
            }
            set {
                this["ThreeDSTSV_歌手変更履歴取得元歌手TSVパス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\ZZXSVMYV\\Desktop\\LINH\\WiiDB\\hailt\\history\\single\\tbl_3DS前回歌手.txt")]
        public string ThreeDSTSV_歌手取込配置ファイル {
            get {
                return ((string)(this["ThreeDSTSV_歌手取込配置ファイル"]));
            }
            set {
                this["ThreeDSTSV_歌手取込配置ファイル"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\ZZXSVMYV\\Desktop\\LINH\\WiiDB\\hailt\\history\\contentbefore\\3DSコンテンツ.tsv")]
        public string ThreeDSTSV_歌手変更履歴取得元コンテンツTSVパス {
            get {
                return ((string)(this["ThreeDSTSV_歌手変更履歴取得元コンテンツTSVパス"]));
            }
            set {
                this["ThreeDSTSV_歌手変更履歴取得元コンテンツTSVパス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\ZZXSVMYV\\Desktop\\LINH\\WiiDB\\hailt\\history\\content\\tbl_3DS前回コンテンツ.txt")]
        public string ThreeDSTSV_コンテンツ取込配置ファイル {
            get {
                return ((string)(this["ThreeDSTSV_コンテンツ取込配置ファイル"]));
            }
            set {
                this["ThreeDSTSV_コンテンツ取込配置ファイル"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\eb-server\\x-drv\\K-tai\\digidoco\\upload\\tsv\\3DS\\3DS_TSV変換.vbs")]
        public string ThreeDSTSV_変換バッチファイル {
            get {
                return ((string)(this["ThreeDSTSV_変換バッチファイル"]));
            }
            set {
                this["ThreeDSTSV_変換バッチファイル"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\XING-MVN\\WiiDB\\output\\ログ\\処理結果.log")]
        public string ThreeDSTSV_変換バッチログファイル {
            get {
                return ((string)(this["ThreeDSTSV_変換バッチログファイル"]));
            }
            set {
                this["ThreeDSTSV_変換バッチログファイル"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\XING-MVN\\WiiDB\\output\\ログ\\TSV出力結果.txt")]
        public string ThreeDSTSV_ログファイル {
            get {
                return ((string)(this["ThreeDSTSV_ログファイル"]));
            }
            set {
                this["ThreeDSTSV_ログファイル"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\XING-MVN\\WiiDB\\output\\収集リスト\\")]
        public string ThreeDSTSV_収集リストパス {
            get {
                return ((string)(this["ThreeDSTSV_収集リストパス"]));
            }
            set {
                this["ThreeDSTSV_収集リストパス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\XING-MVN\\WiiDB\\output\\orch\\")]
        public string UTSV出力_出力パス {
            get {
                return ((string)(this["UTSV出力_出力パス"]));
            }
            set {
                this["UTSV出力_出力パス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\XING-MVN\\WiiDB\\output\\orch\\ログ\\TSV出力結果.txt")]
        public string UTSV出力_ログファイル {
            get {
                return ((string)(this["UTSV出力_ログファイル"]));
            }
            set {
                this["UTSV出力_ログファイル"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:Access\\Wii\\")]
        public string UTSV出力_入力パス {
            get {
                return ((string)(this["UTSV出力_入力パス"]));
            }
            set {
                this["UTSV出力_入力パス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Wii\\recommend_song_")]
        public string UTSV出力_おすすめ曲 {
            get {
                return ((string)(this["UTSV出力_おすすめ曲"]));
            }
            set {
                this["UTSV出力_おすすめ曲"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Wii\\cdn_wjk_total_month_150_")]
        public string UTSV出力_総合ランキング {
            get {
                return ((string)(this["UTSV出力_総合ランキング"]));
            }
            set {
                this["UTSV出力_総合ランキング"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Wii\\year_ranking_.txt")]
        public string UTSV出力_年間ランキング {
            get {
                return ((string)(this["UTSV出力_年間ランキング"]));
            }
            set {
                this["UTSV出力_年間ランキング"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Wii\\ranking_week")]
        public string UTSV出力_ランキングファイル {
            get {
                return ((string)(this["UTSV出力_ランキングファイル"]));
            }
            set {
                this["UTSV出力_ランキングファイル"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Wii\\NAVIDB資料\\TBL_GENRE_SONG.txt")]
        public string UTSV出力_ナビジャンル曲表 {
            get {
                return ((string)(this["UTSV出力_ナビジャンル曲表"]));
            }
            set {
                this["UTSV出力_ナビジャンル曲表"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Wii\\NAVIDB資料\\TBL_GENRE_SINGER.txt")]
        public string UTSV出力_ナビジャンル歌手表 {
            get {
                return ((string)(this["UTSV出力_ナビジャンル歌手表"]));
            }
            set {
                this["UTSV出力_ナビジャンル歌手表"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Wii\\NAVIDB資料\\TBL_SONG.txt")]
        public string UTSV出力_ナビ楽曲マスタ表 {
            get {
                return ((string)(this["UTSV出力_ナビ楽曲マスタ表"]));
            }
            set {
                this["UTSV出力_ナビ楽曲マスタ表"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Wii\\NAVIDB資料\\TBL_SONG_CODE.txt")]
        public string UTSV出力_ナビ選曲番号表 {
            get {
                return ((string)(this["UTSV出力_ナビ選曲番号表"]));
            }
            set {
                this["UTSV出力_ナビ選曲番号表"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Wii\\WU歌手.tsv")]
        public string UTSV出力_比較元歌手TSVパス {
            get {
                return ((string)(this["UTSV出力_比較元歌手TSVパス"]));
            }
            set {
                this["UTSV出力_比較元歌手TSVパス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Orch\\歌手削除チェックファイル.txt")]
        public string UTSV出力_歌手削除チェックファイルパス {
            get {
                return ((string)(this["UTSV出力_歌手削除チェックファイルパス"]));
            }
            set {
                this["UTSV出力_歌手削除チェックファイルパス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1800")]
        public int CONNECT_DDETimeout {
            get {
                return ((int)(this["CONNECT_DDETimeout"]));
            }
            set {
                this["CONNECT_DDETimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public int CONNECT_CmmandTimeOut {
            get {
                return ((int)(this["CONNECT_CmmandTimeOut"]));
            }
            set {
                this["CONNECT_CmmandTimeOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Work")]
        public string Wii_WorkFolder {
            get {
                return ((string)(this["Wii_WorkFolder"]));
            }
            set {
                this["Wii_WorkFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Projects\\2020\\Wii\\bin\\Debug\\Work")]
        public string UTSV出力おすすめ曲パス {
            get {
                return ((string)(this["UTSV出力おすすめ曲パス"]));
            }
            set {
                this["UTSV出力おすすめ曲パス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\{0}\\Maprj\\xing\\orchestra\\TBL_RECOMMENDSONG_CAPIO.txt")]
        public string ImportRecommendSongServerFilePath {
            get {
                return ((string)(this["ImportRecommendSongServerFilePath"]));
            }
            set {
                this["ImportRecommendSongServerFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\maprj\\Wii\\cdn_wjk_total_month_150_{0}.txt")]
        public string UTSV出力総合ランキング {
            get {
                return ((string)(this["UTSV出力総合ランキング"]));
            }
            set {
                this["UTSV出力総合ランキング"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int CONNECT_DDETimeout_CheckConnecting {
            get {
                return ((int)(this["CONNECT_DDETimeout_CheckConnecting"]));
            }
            set {
                this["CONNECT_DDETimeout_CheckConnecting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\{0}\\Maprj\\xing\\orchestra\\TBL_RecommendSong.txt")]
        public string UTSVRecommendSongServerFilePath {
            get {
                return ((string)(this["UTSVRecommendSongServerFilePath"]));
            }
            set {
                this["UTSVRecommendSongServerFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DESKTOP-7U8MJV3\\SQLEXPRESS")]
        public string CONNECT_Server {
            get {
                return ((string)(this["CONNECT_Server"]));
            }
            set {
                this["CONNECT_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wii")]
        public string CONNECT_DBName {
            get {
                return ((string)(this["CONNECT_DBName"]));
            }
            set {
                this["CONNECT_DBName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wii01")]
        public string CONNECT_UserID {
            get {
                return ((string)(this["CONNECT_UserID"]));
            }
            set {
                this["CONNECT_UserID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hailt1234")]
        public string CONNECT_Password {
            get {
                return ((string)(this["CONNECT_Password"]));
            }
            set {
                this["CONNECT_Password"] = value;
            }
        }
    }
}
