//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiiCommon.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Messages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiiCommon.Resources.Resource.Messages", typeof(Resource_Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   処理を続行すると以下のファイルが上書きされます。
        ///{0}
        ///続行してよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A001 {
            get {
                return ResourceManager.GetString("A001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3DSTSV出力基準ファイルを置き換えます。
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A002 {
            get {
                return ResourceManager.GetString("A002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   おすすめ曲情報が未取込ですが、TSVを出力しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A003 {
            get {
                return ResourceManager.GetString("A003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ランキング情報が未取込ですが、TSVを出力しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A004 {
            get {
                return ResourceManager.GetString("A004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み込んだおすすめ曲、Rankingテーブルの内容を削除します。
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A005 {
            get {
                return ResourceManager.GetString("A005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A006 {
            get {
                return ResourceManager.GetString("A006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A007 {
            get {
                return ResourceManager.GetString("A007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A008 {
            get {
                return ResourceManager.GetString("A008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A009 {
            get {
                return ResourceManager.GetString("A009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string A010 {
            get {
                return ResourceManager.GetString("A010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ALERT_TITLE_MESSAGE {
            get {
                return ResourceManager.GetString("ALERT_TITLE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明なエラーが発生しました。管理者に連絡してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E000 {
            get {
                return ResourceManager.GetString("E000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のファイルが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E001 {
            get {
                return ResourceManager.GetString("E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力対象のフォルダが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E002 {
            get {
                return ResourceManager.GetString("E002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同名のファイルが存在します。上書きしてよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E003 {
            get {
                return ResourceManager.GetString("E003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの出力に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E004 {
            get {
                return ResourceManager.GetString("E004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力対象のレコードが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E005 {
            get {
                return ResourceManager.GetString("E005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付の入力フォーマットが不正です。入力例:2008/11/07　→　20081107 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E006 {
            get {
                return ResourceManager.GetString("E006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付の入力フォーマットが不正です。入力例:2008/11/07 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E007 {
            get {
                return ResourceManager.GetString("E007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   操作に必要な権限がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E008 {
            get {
                return ResourceManager.GetString("E008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   過去の日付は指定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E009 {
            get {
                return ResourceManager.GetString("E009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}：{1} が見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E010 {
            get {
                return ResourceManager.GetString("E010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換バッチの実行に失敗しました。変換バッチログを確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E011 {
            get {
                return ResourceManager.GetString("E011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3DSサービス発表日を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E012 {
            get {
                return ResourceManager.GetString("E012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   収集リストは、コンテンツとセットで出力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E013 {
            get {
                return ResourceManager.GetString("E013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力対象を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E014 {
            get {
                return ResourceManager.GetString("E014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力する連番を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E015 {
            get {
                return ResourceManager.GetString("E015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下記の出力対象のフォルダが見つかりません。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E016 {
            get {
                return ResourceManager.GetString("E016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wiiデータ変換＆チェック先フォルダ：{0}が見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E017 {
            get {
                return ResourceManager.GetString("E017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたパスに変換バッチが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E018 {
            get {
                return ResourceManager.GetString("E018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換バッチの実行に失敗しました。変換バッチログを確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E019 {
            get {
                return ResourceManager.GetString("E019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uサービス発表日を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E020 {
            get {
                return ResourceManager.GetString("E020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンテンツランキング用は、コンテンツとセットで出力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E021 {
            get {
                return ResourceManager.GetString("E021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   歌手ランキングは、歌手とセットで出力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E022 {
            get {
                return ResourceManager.GetString("E022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイアップランキングは、タイアップとセットで出力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E023 {
            get {
                return ResourceManager.GetString("E023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   歌手ID変更履歴は、歌手とセットで出力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E024 {
            get {
                return ResourceManager.GetString("E024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uデータ変換＆チェック先フォルダ：{0} が見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E025 {
            get {
                return ResourceManager.GetString("E025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの中身が空の可能性があります。
        ///{0}の取込を中止します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E026 {
            get {
                return ResourceManager.GetString("E026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   21カラム以上の行があったため取り込めませんでした。
        ///{0} 行目 選曲番号：{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E027 {
            get {
                return ResourceManager.GetString("E027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   期間が入力されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E028 {
            get {
                return ResourceManager.GetString("E028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   期間が正しくありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E029 {
            get {
                return ResourceManager.GetString("E029", resourceCulture);
            }
        }
        
        /// <summary>
        ///    {0} 行目   曲ID：{1} に NULLのカラムがあります。
        ///ランキング取込を中止します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E030 {
            get {
                return ResourceManager.GetString("E030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 行目   曲ID：{1} のカラム数が少ないです。
        ///ランキング取込を中止します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E031 {
            get {
                return ResourceManager.GetString("E031", resourceCulture);
            }
        }
        
        /// <summary>
        ///    {0} 行目   曲ID：{1} のカラム数が多いです。
        ///ランキング取込を中止します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E032 {
            get {
                return ResourceManager.GetString("E032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 行目  SONG_GROUPID：{1} に NULLのカラムがあります。
        ///ランキング取込を中止します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E033 {
            get {
                return ResourceManager.GetString("E033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 行目   SONG_GROUPID：{1} のカラム数が少ないです。
        ///ランキング取込を中止します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E034 {
            get {
                return ResourceManager.GetString("E034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 行目   SONG_GROUPID：{1} のカラム数が多いです。
        ///ランキング取込を中止します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E035 {
            get {
                return ResourceManager.GetString("E035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力対象のデータを選択してから実行してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E036 {
            get {
                return ResourceManager.GetString("E036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E037 {
            get {
                return ResourceManager.GetString("E037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   例外が発生しました。
        ///【発生日時】 {0}
        ///【発生箇所】 {1}
        ///【障害内容】 {2}
        ///【備考】エラーログを{3}に出力します。
        ///システム担当者に連絡して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E038 {
            get {
                return ResourceManager.GetString("E038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E039 {
            get {
                return ResourceManager.GetString("E039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E040 {
            get {
                return ResourceManager.GetString("E040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E041 {
            get {
                return ResourceManager.GetString("E041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E042 {
            get {
                return ResourceManager.GetString("E042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E043 {
            get {
                return ResourceManager.GetString("E043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} サーバー上にある{1} データベースに接続できません。データベースが存在し、サーバーが実行中であることを確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E044 {
            get {
                return ResourceManager.GetString("E044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E045 {
            get {
                return ResourceManager.GetString("E045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E046 {
            get {
                return ResourceManager.GetString("E046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E047 {
            get {
                return ResourceManager.GetString("E047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E048 {
            get {
                return ResourceManager.GetString("E048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E049 {
            get {
                return ResourceManager.GetString("E049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E050 {
            get {
                return ResourceManager.GetString("E050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E056 {
            get {
                return ResourceManager.GetString("E056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_TITLE_MESSAGE {
            get {
                return ResourceManager.GetString("ERROR_TITLE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TSV各種：{0} にファイルを出力しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I001 {
            get {
                return ResourceManager.GetString("I001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I002 {
            get {
                return ResourceManager.GetString("I002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   おすすめ曲取込完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I003 {
            get {
                return ResourceManager.GetString("I003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【総合ランキング】
        ///{0} 件取り込みました。
        ///{1} 件失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I004 {
            get {
                return ResourceManager.GetString("I004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【年間ランキング】
        ///{0} 件取り込みました。
        ///{1} 件失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I005 {
            get {
                return ResourceManager.GetString("I005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   操作に必要な権限がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I006 {
            get {
                return ResourceManager.GetString("I006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I007 {
            get {
                return ResourceManager.GetString("I007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I008 {
            get {
                return ResourceManager.GetString("I008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I009 {
            get {
                return ResourceManager.GetString("I009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I010 {
            get {
                return ResourceManager.GetString("I010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INFO_TITLE_MESSAGE {
            get {
                return ResourceManager.GetString("INFO_TITLE_MESSAGE", resourceCulture);
            }
        }
    }
}
